version: "3"
services:
  jupyter:
    build:
      context: .
      target: python
    volumes:
      - .:/workdir
    ports:
      - 8888:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser
  code:
    build:
      context: .
      target: code-server
    ports:
      - 8080:8080
    volumes:
      - ./:/workdir
    entrypoint: "code-server --auth none --bind-addr=0.0.0.0:8080 /app"