version: "3"
services:
  jupyter:
    build:
      context: .
      target: python
    volumes:
      - .:/workdir
    ports:
      - 8888:8888
    command: jupyter notebook --no-browser --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True
  code:
    build:
      context: .
      target: code-server
    ports:
      - 8080:8080
    volumes:
      - ./:/workdir
    entrypoint: "code-server --auth none --bind-addr=0.0.0.0:8080 /workdir"