version: "3.4"
services:
  jupyter:
    image: python:latest
    volumes:
      - .:/workdir
    ports:
      - 8888:8888
    command: jupyter notebook --no-browser --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True
  code:
    image: code-server:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/workdir
    entrypoint: code-server --bind-addr=0.0.0.0:8080 /workdir --env PASSWORD='password' --auth=passowrd